// frameworks.js

const frameworks = [
    "HTML",
    "CSS",
    "JavaScript",
    "Bootstrap",
    "Tailwind",
    "MaterialJs",
    "NodeJs",
    "ExpressJs",
    "Ember",
    "Backbone",
    "jQuery",
    "React.js",
    "React Native",
    "Angular.js",
    "Vue.js",
    "D3.js",
    "Wordpress",
    "Drupal",
    "Joomla",
    "Svelte",
    "Mongo",
    "MongoDB",
    "Django",
    "Flask",
    "Ionic",
    "Spring Boot",
    "Laravel",
    "Rust",
    "Go",
    "Golang",
    "Ruby",
    "Ruby on Rails",
    "ASP.net",
    "PhP",
    "Swift",
    "Kotlin",
    "Micronaut",
    "Flutter",
    "Xamarin",
    "Cocoa",
    "Wicket",
    "Yesod",
    "Nuxt.js",
    "Phoenix",
    "CodeIgniter",
    "PHPixie",
    "Javalin",
    "Silex",
    "Caliburn Micro",
    "PhoneGap",
    "Appcelerator titanium",
    "Swiftic",
    "Native Script",
    "Rachet",
    "MXNet",
    "ML.net",
    "Infer.Net",
    "Chainer",
    "Accord.Net",
    "Horovord",
    "H2O Q",
    "Gauge",
    "Jest",
    "Jasmine",
    "Nightwatch",
    "Protractor",
    "Cypress",
    "Test Project",
    "Galen",
    "Electron",
    "Symfony",
    "Gatsby",
    "Sinatra",
    "CakePHP",
    "Horde",
    "Yii",
    "Zend",
    "Zikula",
    "Grails",
    "Play",
    "Web2py",
    "Lumen",
    "TurboGears",
    "Phalcon",
    "FuelPHP",
    "Grok",
    "Mojolicious",
    "Qt",
    "JavaFX",
    "Unity",
    "Godot",
    "Phaser",
    "Cocos 2d",
    "Unreal Engine",
    "Tensorflow",
    "PyTorch",
    "Numpy",
    "Scikit",
    "Keras",
    "Panda",
    "Pandas",
    "Matplotlib",
    "Apache Spark",
    "Flink",
    "Storm",
    "Openstack",
    "Hadoop",
    "Kubernetes",
    "Docker",
    "Container",
    "Ansible",
    "Puppet",
    "Chef",
    "Terraform",
    "AWS",
    "Azure",
    "Google Cloud",
    "VMWare",
    "Selenium",
    "Junit",
    "TestNG",
    "Mocha",
    "Jest",
    "Pytest",
    "OWASP",
    "Ethereum",
    "Raspberry Pi",
    "Metasploit",
    "Linux",
    "Cisco",
    "Juniper Junos",
    "Power BI",
    "Tableau",
    "Java",
    "C++",
    "C",
    "C#",
    "Python",
    "Git",
    "GitHub",
    "Documentation",
    "Testing",
    "Canva",
    "Adobe"
];

export default frameworks;
