FROM python:3.11-slim-buster

ENV PYTHONUNBUFFERED=1
ENV FLASK_APP=resume_server.py
ENV FLASK_RUN_HOST=0.0.0.0

WORKDIR /app
COPY . /app

RUN pip install -r requirements.txt

EXPOSE 9004

CMD ["flask", "run", "--port", "9004"]